name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jatin4002/chatwoot-custom:latest
          build-args: |
            VITE_ELEVENLABS_AGENT_ID=agent_6601kc1fqeecfc88s7d52jde0syq
            VITE_ELEVENLABS_VOICE_ID=
            VITE_ELEVENLABS_AGENT_NAME=AI Assistant
          cache-from: type=gha
          cache-to: type=gha,mode=max
